### PR TITLE
Fix build on Xcode 11.

### PR DESCRIPTION
**Pull request by cdavis5e**
I missed this.

### CODE REVIEW

**Review by billhollings — APPROVED** [review]
Thanks for catching. I'll try to remember to attempt builds with Xcode 11.7 as well.

**Comment by billhollings** [comment]
What are the reasons for supporting previous Xcode? And how long for?

In the past we haven't supported legacy Xcode's once the current version is out of beta.

**Comment by cdavis5e** [comment]
> What are the reasons for supporting previous Xcode? And how long for?
> 
> In the past we haven't supported legacy Xcode's once the current version is out of beta.

You don't remember? A bunch of clients requested it--including me. Also, at the time, macOS 11 was still in beta, even though Xcode 12 was out of beta, so the final version of Xcode 12 only had macOS 10.15 SDKs.

I suppose at some point we'll need to move to XC12, particularly since that's the first version that supports building for M1 natively. I'll need to discuss this with my coworkers.

**Comment by billhollings** [comment]
I remember the requests based on builds. But I forget the deets, who needs them, and on what platforms. That's why I'm asking.

There are quite a few outstanding issues with iOS builds in Xcode 11 right now (border color for one, and a couple of others). If we're serious about this, we'll need to fix the iOS breakages too. I'll have a stab at it in a bit.

**Comment by billhollings** [comment]
Looks like we'll need somethings like the following in a few places:

```
#if (MVK_MACOS || (MVK_IOS && MVK_XCODE_12))
#endif
```

**Comment by billhollings** [comment]
I've posted a dev poll as issue #1228. Mostly to see whether we should bother with the changes for iOS builds. 

I'm hoping not, because that `#if (MVK_MACOS || (MVK_IOS && MVK_XCODE_12))` macro is starting to get clumsy and fragile.

**Pull request merged**
