### PR TITLE
Mvk cx patched

### PR DESCRIPTION
**Pull request by italomandara**

### CODE REVIEW

**Comment by italomandara** [comment]
@billhollings This Draft was created by mistake, and should be removed from the repo.

**Comment by billhollings** [comment]
> @billhollings Apologies, This Draft was created by mistake, and should be removed from the repo.

No worries. 

Unfortunately, I don't know of any way to fully delete a PR on GitHub. It's closed, but still visible. 

It's fine to leave it like that, but if you need to remove any sensitive content, you'll have to revert the content locally, and force push to this PR again.

**Comment by italomandara** [comment]
> > @billhollings Apologies, This Draft was created by mistake, and should be removed from the repo.
> 
> No worries.
> 
> Unfortunately, I don't know of any way to fully delete a PR on GitHub. It's closed, but still visible.
> 
> It's fine to leave it like that, but if you need to remove any sensitive content, you'll have to revert the content locally, and force push to this PR again.

https://github.com/orgs/community/discussions/35901 You'll need to contact support and open a request, I remembre doing that once but only the owner of the main repo can request that

**Comment by billhollings** [comment]
> they (Github) remove close PRs upon request but only if there's sensitive data exposed and only if the owner of the repo is requesting it.
Just found out, I remember requesting that once so not sure if they limited that when there's sensitive data involved lately.

Do you need it deleted due to sensitive content? And if so, before I submit a support request, are you able to remove it with an amend commit and force push to this PR?

**Comment by italomandara** [comment]
> > they (Github) remove close PRs upon request but only if there's sensitive data exposed and only if the owner of the repo is requesting it.
> > Just found out, I remember requesting that once so not sure if they limited that when there's sensitive data involved lately.
> 
> Do you need it deleted due to sensitive content? And if so, before I submit a support request, are you able to remove it with an amend commit and force push to this PR?

No it's just to not pollute your repo

**Pull request closed without merging**
