### PR TITLE
Enforce barrier when sampling timestamps

### PR DESCRIPTION
**Pull request by PENGUINLIONG**
Some context: https://github.com/KhronosGroup/MoltenVK/issues/2235.

### CODE REVIEW

**Comment by SRSaunders** [comment]
Will there be a performance hit by doing this?  If so, then perhaps it needs to be an optional parm.

**Comment by PENGUINLIONG** [comment]
@SRSaunders Is there anything I could refer to?

**Review by billhollings — APPROVED** [review]
Interesting catch! Good work. And thanks for submitting this fix!

**Comment by billhollings** [comment]
> @SRSaunders Is there anything I could refer to?

This is a good point, and probably the reason we originally set `barrier` to `NO`.

Apple's doc does [indicate](https://developer.apple.com/documentation/metal/mtlrendercommandencoder/3194379-samplecountersinbuffer?language=objc) that it may affect GPU performance, as one would expect from any barrier.

However, the Vulkan spec explicitly [states](https://registry.khronos.org/vulkan/specs/1.3-extensions/man/html/vkCmdWriteTimestamp.html#_description):

> When `vkCmdWriteTimestamp` is submitted to a queue, it defines an execution dependency on commands that were submitted before it, and writes a timestamp to a query pool.

which would indicate that a barrier is required and expected here, and that timestamp scope accuracy is more important than absolute performance.

**Pull request merged**
