### PR TITLE
fix memory management issue in MVKSwapchain

### PR DESCRIPTION
**Pull request by NekoAsakura**
https://github.com/KhronosGroup/MoltenVK/issues/2399
Fix memory management issue in MVKSwapchain

### CODE REVIEW

**Review by cdavis5e — APPROVED** [review]

**Comment by gnattu** [comment]
I'm afraid this change alone is not enough to fix the problem described in #2399. It appears that `CAEDRMetadata` is also a managed objc object which the autorelease pool might trying to release and still cause the double free crash. [Chromium](https://chromium.googlesource.com/chromium/src/+/refs/heads/main/components/metal_util/hdr_copier_layer.mm#351) does not do explicit release on this object and I *think* we should do the same.

This is already reproducible by using mpv with gpu-next and `target-colorspace-hint=yes`, play an HDR file, enter the full screen then quit the full screen, then close the player, you would see a segfault. This segfault disappears after removing the explicit release of `CAEDRMetadata`

**Comment by m154k1** [comment]
> This is already reproducible by using mpv with gpu-next and `target-colorspace-hint=yes`, play an HDR file, enter the full screen then quit the full screen, then close the player, you would see a segfault.

I can confirm this.

> This segfault disappears after removing the explicit release of `CAEDRMetadata`

@gnattu could you please upload the patch?

**Comment by gnattu** [comment]
To test this for mpv it is quite trivial, you just remove this line:
https://github.com/KhronosGroup/MoltenVK/blob/138415d56890aacd1bcdc2477f2219da9f2acbad/MoltenVK/MoltenVK/GPUObjects/MVKSwapchain.mm#L367

But since the autorelease pool might not exist everywhere, I think the more proper way of doing this is to wrap the usage of `CAEDRMetadata` in `@autoreleasepool {...}` block

**Comment by billhollings** [comment]
> I think the more proper way of doing this is to wrap the usage of `CAEDRMetadata` in `@autoreleasepool {...}` block

Fixed in #2436.

**Pull request merged**
