### PR TITLE
Support iOS builds for arm64e architecture.

### PR DESCRIPTION
**Pull request by billhollings**
Fixes issue #431.

### CODE REVIEW

**Comment by DiligentGraphics** [comment]
@billhollings Hmm... I still see the same link errors. It builds fine if I only have arm64 in Architectures. However when I replace it with arm64e, it still fails to link...

**Comment by billhollings** [comment]
@DiligentGraphics 

Okay. Thanks for the feedback.

> I also checked the binary size: it changed from 10.3 Mb to 10.4 Mb (not sure if it is related to this change). Does that sound reasonable?

Yeah...I noticed almost no size change myself. I was expecting a more typical fat binary...something along the lines of twice the original size. I'm not sure if that is because both `arm64` architectures can share a lot of compiled code...or because it's actually not including `arm64e` for some reason.

Unfortunately I am not able to test `arm64e` on a device directly myself yet. As it sits now...the MoltenVK projects **_should_** be building for both architectures. Let's see what additional results arise from further testing as these devices and apps built for them become more common.

**Comment by DiligentGraphics** [comment]
I tried to remove arm64 architecture completely and build arm64e only by editing xcode project files (I still do not know where these settings are hidden in the IDE). So when I removed arm64, the project failed to build.
There was also this warning:

```
None of the architectures in ARCHS (arm64) are valid for this target. Consider setting ARCHS to $(ARCHS_STANDARD) or updating it to include at least one value from VALID_ARCHS (arm64e). (in target 'MoltenVK-iOS')
```

Shouldn't you also update Architectures? As far as I understand, the intersection of Architectures and Valid Architectures get built.

**Comment by sanvital** [comment]
> 
> > I also checked the binary size: it changed from 10.3 Mb to 10.4 Mb (not sure if it is related to this change). Does that sound reasonable?
> 
> Yeah...I noticed almost no size change myself. I was expecting a more typical fat binary...something along the lines of twice the original size. I'm not sure if that is because both `arm64` architectures can share a lot of compiled code...or because it's actually not including `arm64e` for some reason.
> 

This is an old thread (and it's basically dead given the merge), but I felt inspired to share my theory for the suspiciously small change on the size of the binary. I believe this observation is due to the fact that the arm64e slice refuses to support bitcode. If you `lipo -detailed_info` a universal executable you will note that the mac slices (i.e. simulator) are similarly small, as they also eschew bitcode.

I found this thread on the Apple developer forums, and added my two cents: [How to create arm64e slice with bitcode enabled?](https://forums.developer.apple.com/thread/125160). The answer, as far as I know, you cannot.

**Pull request merged**
