### PR TITLE
MVKCmdResolveImage: Use layered rendering where possible.

### PR DESCRIPTION
**Pull request by cdavis5e**

### CODE REVIEW

**Comment by cdavis5e** [comment]
Surprisingly, this is actually a bit slower in the CTS, by about 10-30 ms, than resolving layers one at a time--at least, after the first test which resolves multiple layers, which takes about the same amount of time. I wonder if I should just withdraw this change.

**Review by billhollings — APPROVED** [review]
👍🏻

**Comment by billhollings** [comment]
>I wonder if I should just withdraw this change.

Let me know whether to pull this in.

**Comment by cdavis5e** [comment]
I'm not sure it'll hurt in practice--I don't think we'll see a string of arrayed `vkCmdResolveImage()` calls in practice. And maybe it'll actually help in some cases. Feel free to pull it in.

**Pull request merged**
