### PR TITLE
MVKImage: Always use a texel buffer for atomic storage images.

### LINKED ISSUE #1766: Fix `shaderAtomicOperationLocal` test failures
This is in support of a Khronos contract to reduce CTS failures in MoltenVK, leading up to certification as a Vulkan Portability implementation.

As I said in the [Vulkan Portability issue](https://github.com/KhronosGroup/Vulkan-Portability/issues/49), the problem is that no underlying buffer was passed to the shader. The reason is that these images use `OPTIMAL` tiling, so there is no backing buffer (i.e. `MTLTexture.buffer` returns `nil`). We can fix that by having `OPTIMAL` images with `STORAGE_IMAGE` usage also use a texel buffer. It won't quite be "optimal," but it will allow image atomics to work.

Two CTS failures will be fixed by this change.

### PR DESCRIPTION
**Pull request by cdavis5e**
Do this even if `OPTIMAL` tiling were requested. Vulkan mandates support for image atomics on `OPTIMAL`-tiled `R32_UINT` and `R32_SINT` images. In a way, this is "optimal"; image atomics won't work without this.

Advertise support for atomics on `OPTIMAL` tiled images now.

Fixes at least two CTS tests under
`dEQP-VK.compute.basic.image_atomic_op_*`.

Closes #1766.

### CODE REVIEW

**Review by billhollings — COMMENTED** [review]
LGTM. But the error @phush0 posted needs assessment.

**Comment by cdavis5e** [comment]
> I've got this when trying game with DXVK:

Which game? Do you have the log files?

**Comment by phush0** [comment]
If you want logs with specific options tell me . Game is Guild Wars 2 free to play. Error is strating app at all.

**Comment by cdavis5e** [comment]
@phush0 I figured it out. We weren't using the correct alignment for linear-for-atomics textures that are nominally `OPTIMAL`. Try it now.

**Comment by phush0** [comment]
new result 

```
-[MTLDebugBuffer newTextureWithDescriptor:offset:bytesPerRow:]:271: failed assertion `New Texture With Descriptor Validation
linear texture arrayLength(6) must be 1
'
warn:  D3D11DXGIDevice::QueryInterface: Unknown interface query
warn:  a7aa6116-9c8d-4bba-9083-b4d816b71b78
```

**Comment by cdavis5e** [comment]
@phush0 Try it now.

**Comment by phush0** [comment]
```
validateNewTexture:60: failed assertion `Buffer-backed textures must have a texture type of MTLTextureType2D, MTLTextureTypeTextureBuffer or MTLTextureType2DArray, found MTLTextureType3D.'
```

**Comment by cdavis5e** [comment]
@phush0 Third time's the charm...

**Comment by phush0** [comment]
Works now. Good job!!!

**Comment by billhollings** [comment]
@cdavis5e Thanks for the fix!
@phush0 Thanks for testing it!

**Pull request merged**
