### PR TITLE
Feature widelines

### PR DESCRIPTION
**Pull request by jarrodnorwell**

### CODE REVIEW

**Comment by jarrodnorwell** [comment]
Ignore, sent PR to wrong repo

**Comment by billhollings** [comment]
@jarrodnorwell 

Interesting PR.

```
void MVKLineWidthCommandEncoderState::encodeImpl(uint32_t stage) {
    if (stage != kMVKGraphicsStageRasterization) { return; }
    if (!_cmdEncoder->_pDeviceFeatures->wideLines) { return; }
    if (![_cmdEncoder->_mtlRenderEncoder respondsToSelector: @selector(setLineWidth:)]) { return; }
    [(id<MVKMTLRenderCommandEncoderLineWidth>)_cmdEncoder->_mtlRenderEncoder setLineWidth: _lineWidth];
}
```

I assume that `[MTLRenderCommandEncoder setLineWidth:]` is a private Metal API method?

> Ignore, sent PR to wrong repo

If you have a fork repo where you are accumulating use of Metal's private API, it might be good to bring them into the main MoltenVK repo, with an appropriate compile guard macro, such as `MVK_USE_METAL_PRIVATE`, that could be enabled when building MoltenVK.

Enabling that build setting would almost certainly disqualify an app from distribution via the App Store, but for macOS games that are distributed directly, these features would be functional. And it would give us a basis for requesting Apple to open up some of those private API's.

Are you interested in discussing this?

**Comment by jarrodnorwell** [comment]
Hey @billhollings,

This is actually an accumulation of patches from @cdavis5e and eventually @js6i with their Geometry Shader fork, I'm hoping to bring better support to my Yuzu port for iOS (as well as my Citra port to the same platform)

My plan wasn't to merge it into the main repository as it does use private API's as you mentioned and my apps won't be made available on the AppStore

**Comment by billhollings** [comment]
> This is actually an accumulation of patches from @cdavis5e and eventually @js6i with their Geometry Shader fork

@jarrodnorwell @cdavis5e @js6i 

As I mention above, it might be helpful to be able to pull these into MoltenVK main, wrapped in a guard macro.

Can we get access to these patches? And/or a list of private functionality that has been added?

**Comment by billhollings** [comment]
Hmmm...I had forgotten that we'd travelled down this road before in #1657 and #1670. 🤦🏻‍♂️

I'll do further follow up there.

**Comment by billhollings** [comment]
PR #2137 has added this functionality.

**Pull request closed without merging**
