### PR TITLE
Development support for future VK_KHR_portability_subset_metal extension.

### PR DESCRIPTION
**Pull request by billhollings**
- `fetchDependencies` script pulls `VK_KHR_portability_subset_metal` content from private Khronos repo.
- Add `VK_KHR_portability_subset_metal` extension.
- Include `VkPhysicalDevicePortabilitySubsetMetalFeaturesKHR` in `pNext` of `VkPhysicalDeviceFeatures2`.

### CODE REVIEW

**Comment by billhollings** [comment]
GitHub CI is failing because it doesn't have access to the private Khronos repo. This is expected.

**Review by aitor-lunarg — APPROVED** [review]
LGTM! Thank you!

**Comment by alyssarosenzweig** [comment]
> shaderImageGatherExtendedConstOffsets

This is straightforward to lower, as most native drivers do?

**Comment by cdavis5e** [comment]
> > shaderImageGatherExtendedConstOffsets
> 
> This is straightforward to lower, as most native drivers do? https://gitlab.freedesktop.org/mesa/mesa/-/blob/main/src/compiler/nir/nir_lower_tex.c?ref_type=heads#L1253

Sadly, not as straightforward as one would like. It's simple enough to expand it to four `texture::read()` calls, but the problem is handling sampler coordinate wrapping. We can't introspect the `sampler` object for its wrap modes, so we'd have to pass this information alongside the sampler. This becomes particularly problematic when not using argument buffers, which we don't at all by default.

**Comment by alyssarosenzweig** [comment]
> > > shaderImageGatherExtendedConstOffsets
> > 
> > 
> > This is straightforward to lower, as most native drivers do? https://gitlab.freedesktop.org/mesa/mesa/-/blob/main/src/compiler/nir/nir_lower_tex.c?ref_type=heads#L1253
> 
> Sadly, not as straightforward as one would like. It's simple enough to expand it to four `texture::read()` calls, but the problem is handling sampler coordinate wrapping. We can't introspect the `sampler` object for its wrap modes, so we'd have to pass this information alongside the sampler. This becomes particularly problematic when not using argument buffers, which we don't at all by default.

See the linked lowering. You turn it into 4 gathers

**Comment by billhollings** [comment]
> > See the linked lowering. You turn it into 4 gathers
> 
> Thanks for the suggestion, and example. I've added it to the full [issue discussion](https://github.com/KhronosGroup/Vulkan-Portability/issues/31#issuecomment-2009450000).

SPIRV-Cross PR [#2325](https://github.com/KhronosGroup/SPIRV-Cross/pull/2325) adds support for image gather with ConstOffsets.

**Pull request merged**
