### PR TITLE
WIP: VK_EXT_mesh_shader

### PR DESCRIPTION
**Pull request by BeastLe9enD**
I'm adding mesh shader support to MoltenVK together with @zmarlon based on https://github.com/Try/Spirv-Cross/tree/msl-mesh-shader .
At the moment, it is not very functional at all, only a basic triangle is rendering.

### CODE REVIEW

**Comment by BeastLe9enD** [comment]
@billhollings Yes, that would be a nice idea!

**Comment by billhollings** [comment]
> @billhollings Yes, that would be a nice idea!

I've created a `mesh-shader` [branch](https://github.com/KhronosGroup/MoltenVK/tree/mesh-shader). Please redirect this PR to it.

**Comment by alexsch01** [comment]
Any update on this PR? This is amazing

**Comment by BeastLe9enD** [comment]
@alexsch01 There are still a few things that need to be done to get the PR ready. For example, the properties and features structures still need to be filled, and it hasn't been extensively tested yet, for example the task shader implementation hasn't been tested apart from a simple dummy task shader. Also, we are still waiting for the pull request that implements MSL mesh shaders in Spirv-Cross to be merged. There are still problems here, as HLSL mesh shaders for example do not yet work at all with the Spirv-Cross version. In the meantime, if anyone wants to test their own mesh and task shaders, they are welcome to do so and feedback is always appreciated.

**Comment by BeastLe9enD** [comment]
I have updated the branch. Could you reset the mesh-shader branch to the current main state? Then there would be no more merge conflicts and we could merge the part into the mesh_shader branch 🙂 @billhollings

**Comment by BeastLe9enD** [comment]
Hope it's not rude to tag u another time @billhollings . If you haven't missed it by accident, just ignore it :)

**Comment by billhollings** [comment]
> Hope it's not rude to tag u another time

No worries. I do sometimes need reminding. 😉

> Could you reset the mesh-shader branch to the current main state?

You should be able to do this yourself. That way you can fix any conflicts in a way that is compatible with your branch work, rather than have me try to arbitrate any conflicts.

Is there a reason why you need me to do it?

**Comment by BeastLe9enD** [comment]
> You should be able to do this yourself. 
My plan was just to rebase [KhronosGroup:mesh-shader](https://github.com/KhronosGroup/MoltenVK/tree/mesh-shader) to main and then merge my PR into the main, but I have no access to do so

**Comment by billhollings** [comment]
Sorry...that was my bad. I was confusing the PR with the branch.

The `mesh-shader` branch is up to date now.

**Comment by BeastLe9enD** [comment]
@billhollings can you change the head branch from `ProjectKML:main` zu `ProjectKML:mesh_shader` ? I can only change the base branch.

**Comment by billhollings** [comment]
> @billhollings can you change the head branch from `ProjectKML:main` zu `ProjectKML:mesh_shader` ? I can only change the base branch.

I'm not sure I understand what you are asking? Do you mean you have moved your forked and modified code from `ProjectKML:main` to `ProjectKML:mesh_shader`, and you want this PR to pull from `ProjectKML:mesh_shader` now?

If so, I can't find any way to do that. Let me know if you know of a way to do that.

BTW...it would be much better to update the 123 commits into the `MoltenVK::mesh-shader` branch via a separate PR that does just that, instead of combining it into this enhancement PR, otherwise we can't tell what's actually in this PR. 

If you don't have permissions to do that, I can take care of it.

**Comment by BeastLe9enD** [comment]
@billhollings 
> Do you mean you have moved your forked and modified code from `ProjectKML:main` to `ProjectKML:mesh_shader`

yep, thats what I mean. Unfortunately I cannot change it too, thats why I though maybe you have the permission to do. But if you cannot do it, it looks like github does not have the feature and I have to make a new pull request.

> BTW...it would be much better to update the 123 commits into the MoltenVK::mesh-shader branch via a separate PR that does just that, instead of combining it into this enhancement PR, otherwise we can't tell what's actually in this PR.

yea good point, I have no permission so it would be nice if you do this :)

**Comment by billhollings** [comment]
> yea good point, I have no permission so it would be nice if you do this :)

Done.

**Pull request merged**
