### PR TITLE
Initial support for Metal 3.0.

### PR DESCRIPTION
**Pull request by billhollings**
- Add MVKPhysicalDevice functions to support new MTLDevice methods supportsVersion: and supportsFamily:.
- MVKPhysicalDevice tests for Metal 3.0 & MSL 2.2.
- Move some global functions into the MVKPhysicalDevice class.
- Support Xcode 11.

### CODE REVIEW

**Comment by billhollings** [comment]
Travis doesn't support Xcode11 yet. Merging anyway.

**Comment by danginsburg** [comment]
Does this mean we need to switch to Xcode 11 to compile MoltenVK now?

**Comment by cdavis5e** [comment]
> Does this mean we need to switch to Xcode 11 to compile MoltenVK now?

Only on this branch, for now.

**Comment by billhollings** [comment]
> > Does this mean we need to switch to Xcode 11 to compile MoltenVK now?
> 
> Only on this branch, for now.

I expect we'll wait until sometime after macOS 10.15, iOS 13, & Xcode 11 are all officially released and out of Beta...which typically happens sometime in late fall...before we merge the `Metal-3.0` branch into `master`.

**Comment by oscarbg** [comment]
as said in other thread still hope we get a 1.0.37 (Vulkan SDK 1.1.121) Metal 3.0 release as seems mac is delayed to October but we have have today Xcode 11 GM..

**Comment by billhollings** [comment]
> hope we get a 1.0.37 (Vulkan SDK 1.1.121) Metal 3.0 release

I'll merge and package an SDK 1.1.121 release on the Metal-3.0 branch tomorrow.

**Comment by oscarbg** [comment]
great.. thanks @billhollings !

**Comment by oscarbg** [comment]
@billhollings time to merge Metal 3.0 branch into master branch?

**Comment by billhollings** [comment]
> I'll take care of it by the end of the week.

PR #758 merges Metal 3.0 branch into master.

**Pull request merged**
