### PR TITLE
Merge xcode12 branch into master.

### PR DESCRIPTION
**Pull request by billhollings**
The introduction of Apple Silicon complicates the building of fat libraries that span both devices and simulators, because such fat libraries would have two distinct sets of arm64 code. 

To properly support the diverse combinations of platforms and architectures available on Apple devices and runtime environments, this update changes the linking options available in MoltenVK to be based on an XCFramework that 
covers all combinations of platforms and architectures, and dynamic libraries that each cover multiple architectures (arm64/arm64e/x86_64) on a single platform (macOS/iOS/tvOS).

This update removes the use of fat dynamic and static libraries that try to cover both devices and Simulators.

It turns out that Xcode prior to Xcode 12 is affected by an internal [race condition](https://pyckamil.github.io/programming,/xcframework,/xcode/2020/05/09/everything-wrong-with-xcframeworks.html) when building with `XCFrameworks` that are used by multiple targets.

This `XCFramework` race condition is fixed in Xcode 12.

To allow MoltenVK to build in Xcode 11, the `MoltenVKShaderConverter` frameworks have been refactored to combine `MoltenVKSPIRVToMSLConverter` and `MoltenVKGLSLToSPIRVConverter` frameworks into a single `MoltenVKShaderConverter` framework, so that each `XCFramework` dependency is only used once. This has the desirable additional effect of simplifying the `MoltenVKShaderConverter` project organization.

MoltenVK with `XCFrameworks` now builds on Xcode 11.7, 12.0, and 12.2 beta.

### CODE REVIEW

**Comment by cdavis5e** [comment]
I'm not sure this should go in yet. The released version of Xcode 12 only has a 10.15.6 SDK, so it might be missing `MTLLanguageVersion2_3`. Let me check on that, just as soon as this download is finished (I'm using the 12.2 beta).

**Comment by billhollings** [comment]
> missing MTLLanguageVersion2_3

Yeah...I worked around it in this release. A future release can add `MTLLanguageVersion2_3` back in for macOS.

With the move to 1.1 and portability, etc., this SDK release will be significant, and I figured it would be a good time to also rework how applications link. It has to happen sometime very soon, and I figured this was the best time.

**Comment by cdavis5e** [comment]
Admittedly, there's another reason I want to hold on this for now. We are busy working on CrossOver 20--it's in beta now--and I want to merge MVK 1.1 in so I can take advantage of all the new features and fixes.

The thing is, our build system currently runs Mojave and uses a strange mix of Xcode 9, 10, and 11. Part of the problem is that we also need to build some things for 32-bit (not including MoltenVK, since Metal doesn't support 32-bit code). Having to also support Xcode 12 would make things even more complicated, especially this late in the release. For this reason, I want to hold off on this until all my other patches are merged. After #1051, #1052, and #1053, I have about five more patches I want to merge. I definitely want to see this merged in time for the SDK, though the new build system stuff will probably make life harder at first for LunarG, too. 😃

**Comment by richard-lunarg** [comment]
>I definitely want to see this merged in time for the SDK,
>though the new build system stuff will probably make life harder at first
for LunarG, too. 😃

I've also found a minor build problem with SPIRV-Tools w/XCode 12.

https://github.com/KhronosGroup/SPIRV-Tools/issues/3825

There may be more. I'm looking at a worst case scenario of building most of
the SDK with 11.7 and MoltenVK with 12 if need be. I was pretty happy that
we could put the iOS fat binaries in this round, it would be icing on the
cake to have support for Apple Silicon in there though. Oh... and I guess
we'd need that for the layers too. This might be a tall order for less than
a week to go before SDK builds start. I'm looking at it now and we'll see
how much we can get in.


Richard S. Wright Jr.
Sr. Graphics Software Engineer
LunarG, Inc. - 3D Graphics Software Solutions
richard@lunarg.com
321-262-9049

**Comment by billhollings** [comment]
@cdavis5e 

>I definitely want to see this merged in time for the SDK

By "this" are you referring to this PR #1054, or are you referring collectively to the several patches you are currently working on?

@cdavis5e @richard-lunarg 

>Having to also support Xcode 12 would make things even more complicated

>I've also found a minor build problem with SPIRV-Tools w/XCode 12.

I hear you both.

To clarify, is Xcode 12 the primary concern? Currently, the only need for Xcode 12 is `MTLLanguageVersion2_3`. I should be able to conditionally compile around that value, which would allow the build to run in Xcode 11.7.

The bigger structural change is really the move to `XCFrameworks` and the new library destinations (ie. `dylib/macOS/libMoltenVK.dylib` instead of `macOS/dynamic/libMoltenVK.dylib`). Is that a concern too for this release?

Summarizing...if we can build in Xcode 11.7 with this PR included, are there any other concerns with this PR at this point in the release cycle?

**Comment by Gcenx** [comment]
@billhollings if it’s possibly build using Xcode11.7 that would be handy since it’s possible to use Xcode11.7 on Mojave.

@cdavis5e that sounds good and would resolve some other issues\
I’m confused by your build system requiring XCode9/10/11 on Mojave when I’m only using Mojave with Xcode11.7 using MacOSX10.13.sdk for build dependencies and a modified MacOSX10.14.sdk to support 32Bit builds (wine)

**Review by cdavis5e — APPROVED** [review]
> Summarizing...if we can build in Xcode 11.7 with this PR included, are there any other concerns with this PR at this point in the release cycle?

No. Looks good. 👍

**Comment by billhollings** [comment]
@cdavis5e @richard-lunarg 

MoltenVK with `XCFrameworks` now builds on Xcode 11.7, 12.0, and 12.2 beta, and `MTLLanguageVersion2_3` is supported appropriately in each build environment.

Enabling support for Xcode 11.7 required a beneficial and simplifying restructuring of the `MoltenVKShaderConveter` project organization to get around an internal [race condition](https://pyckamil.github.io/programming,/xcframework,/xcode/2020/05/09/everything-wrong-with-xcframeworks.html) when using Xcode versions prior to Xcode 12 for building with `XCFrameworks` that are used by multiple targets.

Unless there are any other concerns (other than the requirement for Xcode 11.7), this PR should be good to be included. Speak now if there are concerns!

@richard-lunarg For building the SDK, once this PR is pull in, the subpath to the `libMoltenVK.dylb` will now be `dylib/macOS/libMoltenVK.dylb` instead of the previous `macOS/dynamic/libMoltenVK.dylb`

**Comment by richard-lunarg** [comment]
> @richard-lunarg For building the SDK, once this PR is pull in, the subpath to the `libMoltenVK.dylb` will now be `dylib/macOS/libMoltenVK.dylb` instead of the previous `macOS/dynamic/libMoltenVK.dylb`

Thanks @billhollings . Currently my build scripts are failing (naturally).  I was thinking I should wait for dust to settle before reporting anything. ./fetchdependencies in particular is failing too. I'll pull from this branch right now and see if there are still any problems.

**Comment by billhollings** [comment]
@richard-lunarg 

>Currently my build scripts are failing (naturally). I was thinking I should wait for dust to settle before reporting anything. ./fetchdependencies in particular is failing too.

What's failing, and under what version of Xcode? 

You mentioned SPIRV-Tools. What version of SPIRV-Tools are you attempting to integrate?

**Comment by richard-lunarg** [comment]
@billhollings 
> What's failing, and under what version of Xcode?

XCode 12... but I think it's a moot point. Using this branch it got past the previous error (still using the same glslang LNG commit from the last SDK). I was previously pulling MoltenVK right off of master. Once you merge this PR, I think we should be good to go!

**Comment by billhollings** [comment]
@richard-lunarg 

>XCode 12...

With this PR, you can use either Xcode 11.7 or Xcode 12...whichever works for you.

**Pull request merged**
