### PR TITLE
OLD:  Improve support for iOS App Store rules by using dynamic XCFramework.

### PR DESCRIPTION
**Pull request by billhollings**
Apple's iOS App Store does not permit an app to link to naked `dylibs`. Instead, these must be placed in frameworks, which are embedded in a dynamic version of `MoltenVK.xcframework`.

- Move static XCFramework, containing `libMoltenVK.a` static libraries, to `Package/Latest/MoltenVK/static/MoltenVK.xcframework`.
- Generate dynamic XCFramework, containing `MoltenVK.framework` dynamic libraries, in `Package/Latest/MoltenVK/dynamic/MoltenVK.xcframework`.
- Always run MoltenVK build scripts, to ensure all components are added to the XCFrameworks, and `MoltenVK/Package` is always refreshed, even if code compilation is not required.
- Consolidate scripts `copy_to_staging.sh` and `copy_lib_to_staging.sh`.
- Fix `make install` to correctly install `/usr/local/lib/libMoltenVK.dylib` on macOS.
- Cube demo link to dynamic `MoltenVK.framework` through `MoltenVK.xcframework`, instead of to naked `libMoltenVK.dylib`.
- Update `README.md` and `MoltenVK_Runtime_UserGuide.md` documents.

@richard-lunarg

### CODE REVIEW

**Comment by richard-lunarg** [comment]
Fetch dependencies is failing for me too.

========== glslang and SPIRV-Tools ==========

*** ERROR ***
stderr contains:
Cloning into 'cereal'...
Note: switching to '51cbda5f30e56c801c07fe3d3aba5d7fb9e6cca4'.

You are in 'detached HEAD' state. You can look around, make experimental
changes and commit them, and you can discard any commits you make in this
state without impacting any branches by switching back to a branch.

If you want to create a new branch to retain commits you create, you may
do so (now or later) by using -c with the switch command. Example:

  git switch -c <new-branch-name>

Or undo this operation with:

  git switch -

Turn off this advice by setting config variable advice.detachedHead to false

HEAD is now at 51cbda5f Merge branch 'develop' for release 1.2.2
Cloning into 'SPIRV-Cross'...
Note: switching to '64f64c837a8ba7e32e91cebcc6c796e9b45ab186'.

You are in 'detached HEAD' state. You can look around, make experimental
changes and commit them, and you can discard any commits you make in this
state without impacting any branches by switching back to a branch.

If you want to create a new branch to retain commits you create, you may
do so (now or later) by using -c with the switch command. Example:

  git switch -c <new-branch-name>

Or undo this operation with:

  git switch -

Turn off this advice by setting config variable advice.detachedHead to false

HEAD is now at 64f64c83 Merge pull request #2266 from KhronosGroup/pr-2257
checkdir:  cannot create extraction directory: glslang/External/spirv-tools
           No such file or directory

**Comment by billhollings** [comment]
> Fetch dependencies is failing for me too.

@richard-lunarg I missed updating the XCFrameworks for the dependencies in the initial PR.

It's fixed, and should be good now.

**Comment by richard-lunarg** [comment]
@billhollings Yes, building fine now. I'll do some additional tests on this today.

**Comment by richard-lunarg** [comment]
For app store compatibility, we still need to remove the symbolic link to libMoltenVK.dylib. Here's a screen shot from the App Store validation tool:

image

**Comment by richard-lunarg** [comment]
A couple other details.
It's okay to put the MoltenVK.json in /MoltenVK/Package/Release/MoltenVK/dynamic/dylib/macOS, just don't put it inside the framework.
The iOS framework (simulator and hardware) have a folder "Template.framework" that is likely not intended.

Aside: I'm having trouble building just the iOS simulator target.
"ld: -platform_version unknown platform: macos-simulator"
But this only happens when I build from Python, not the command line, so I'm still investigating that.
The tvOS simulator (dynamic library) is also "missing" or someplace I can't find it. Also investigating, but thought I'd mention it in case it "rings a bell".

**Pull request closed without merging**
