### PR TITLE
Update shader caching for compatibility with texture swizzling.

### PR DESCRIPTION
**Pull request by billhollings**
MVKPipelineLayout set auxiliary buffer MSL index relative to already-calculated
push constant buffer MSL index.
MVKPipeline destructor release auxiliary buffer MTLBuffer instance.
Nudge MVK_VERSION_PATCH.

### CODE REVIEW

**Comment by billhollings** [comment]
@cdavis5e 

Unfortunately the swizzle enhancements in PR #303 broke Dota2 and the [Cinder Fish Tornado](https://github.com/brenwill/Cinder) demo.

Repairs in this PR to MoltenVK's shader caching and look-ups with the new shader parameters that you introduced has fixed the Data2 problems.

Before I merge, can you check out this PR and ensure that the changes here do not harm the apps you were testing against with your original changes, please?

With the swizzle enhancement, the Fish Tornado demo is now triggering a `Cannot yet map non-aliased parameter to Metal resource!` error from within `SPIRV-Cross`. I'm going to pull out the offending shaders and work on them in `SPIRV-Cross`. In the meantime, if you have any insights about what might cause that error, let me know.

Thanks.

**Comment by cdavis5e** [comment]
> With the swizzle enhancement, the Fish Tornado demo is now triggering a `Cannot yet map non-aliased parameter to Metal resource!` error from within `SPIRV-Cross`. I'm going to pull out the offending shaders and work on them in `SPIRV-Cross`. In the meantime, if you have any insights about what might cause that error, let me know.
This error occurs when a sampled image is passed as a parameter to a function instead of being used as a global. ("Non-aliased" is because globals are lowered to function parameters in MSL--they "alias" the original globals. Parameters like this one that were present in the original SPIR-V don't.) Because any of the images the shader uses could conceivably be passed here, SPIRV-Cross can't figure out what its index in the texture argument table is, so it doesn't know which swizzle constant it needs to use here. One solution might be to pass the argument index along with the image; then in the function, use the parameter to look up the swizzle constant. Another might be to pass the swizzle constant itself.

**Comment by billhollings** [comment]
@cdavis5e 

Thanks for the info about texture handling. Do you mean when the texture is passed as a function parameter within SPIR-V...as opposed to passed as a function parameter within MSL...which happens all the time in SPIRV-Cross because MSL has no globals?

Let me know once you've tested this PR against your test apps...since this PR changes some of the behaviour of your original design...in particular how the texture count and aux buffer MSL index is determined (I used a reference to the push constant indices that were already being calculated...and removed your map-construction code). I want to make sure I haven't broken anything on your side in the process before merging this PR.

Also...I have a few questions about the operation of the swizzling data and it would be good to have a short design discussion so I can understand some of the design requirements that went into the swizzling enhancement. Rather than address it here...I'll open a separate issue for that discussion.

**Comment by billhollings** [comment]
Fixes issue #308.

**Pull request merged**
